version: '2.1'

services:
  master:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_master"
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'citus:9.2.2'
    ports: ["${MASTER_EXTERNAL_PORT:-5432}:5432"]
    environment: &AUTH
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDB: postgres
    labels: ['com.citusdata.role=Master']
    volumes:
      - pgdata_master:/var/lib/postgresql/data

  worker1:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'citus:9.2.2'
    environment: *AUTH
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    volumes:
      - pgdata_worker1:/var/lib/postgresql/data

  worker2:
    build:
      context: ./
      dockerfile: Dockerfile
    image: 'citus:9.2.2'
    environment: *AUTH
    labels: ['com.citusdata.role=Worker']
    depends_on: { manager: { condition: service_healthy } }
    volumes:
      - pgdata_worker2:/var/lib/postgresql/data

  manager:
    container_name: "${COMPOSE_PROJECT_NAME:-citus}_manager"
    build:
      context: ../membership-manager
      dockerfile: Dockerfile
    image: 'citus-manager:0.2.0'
    volumes: ['/var/run/docker.sock:/var/run/docker.sock']
    environment: *AUTH
    depends_on: { master: { condition: service_healthy } }

volumes:
  pgdata_master:
  pgdata_worker1:
  pgdata_worker2: